# HSE 2023: Mathematical Methods for Data Analysis

## Homework 1

### Attention!
* For tasks where <ins>text answer</ins> is required **Russian language** is **allowed**.
* If a task asks you to describe something (make conclusions) then **text answer** is **mandatory** and **is** part of the task
* **Do not** upload the dataset (titanic.csv) to the grading system (we already have it)
* We **only** accept **ipynb** notebooks. If you use Google Colab then you'll have to download the notebook before passing the homework
* **Do not** use python loops instead of NumPy vector operations over NumPy vectors - it significantly decreases performance (see why https://blog.paperspace.com/numpy-optimization-vectorization-and-broadcasting/), will be punished with -0.25 for **every** task.
Loops are only allowed in part 1 (Tasks 1 - 4).
* Some tasks contain tests. They only test your solution on a simple example, thus, passing the test does **not** guarantee you the full grade for the task.

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Python (2 points)

**Task 1** (0.5 points)<br/>
Enter nonzero numbers `a`, `d` and `N`. Find the sum of the first `N` members of [harmonic sequence](https://en.wikipedia.org/wiki/Harmonic_progression_(mathematics)) with the first member denominator `a`

In [3]:
def find_sum(a: int, d: int, N: int) -> float:    
    return np.sum(1.0 / np.arange(1, N+1))

a = 1
d = 1
N = 10
print(find_sum(a, d, N))

2.9289682539682538


**Task 2** (0.5 points) <br/>
Enter an integer number `N`. Check if it is a palindrome number **without converting it to the string**. It means that it can be read equally from left to right and from right to back.

In [10]:
def check_palindrome(N):
    rev = 0
    temp = N
    while temp != 0:
        rev = rev * 10 + temp % 10
        temp = temp // 10
    return np.equal(N, rev)

for N in [3, 81, 111, 113, 810, 2022, 4774, 51315, 611816]:
    print(N, check_palindrome(N))

3 True
81 False
111 True
113 False
810 False
2022 False
4774 True
51315 True
611816 False


**Task 3** (0.5 points) <br/>
Find the first `N` palindrome numbers starting from 42 (you may use the function from the precious task).

In [23]:
def find_palindromes(N):
    curr = 42
    res = []
    while N != 0:
        if check_palindrome(curr):
            N -= 1
            res.append(curr)
        curr += 1
    return res

print(find_palindromes(3))
print(find_palindromes(13))
print(find_palindromes(23))

[44, 55, 66]
[44, 55, 66, 77, 88, 99, 101, 111, 121, 131, 141, 151, 161]
[44, 55, 66, 77, 88, 99, 101, 111, 121, 131, 141, 151, 161, 171, 181, 191, 202, 212, 222, 232, 242, 252, 262]


**Task 4** (0.5 points) <br/>
There are numbers: `a`, `b`, `c`. Without using functions `min`, `max` and other functions, find the median number.

In [24]:
from random import randint

def find_median(a, b, c):
    if a >= b and b >= c or c >= b and b >= a:
        return b
    elif a >= c and c >= b or b >= c and c >= a:
        return c
    return a

for i in range(10):

    a = randint(-100, 100)
    b = randint(-100, 100)
    c = randint(-100, 100)

    print(a, b, c, '\tMedian:', find_median(a, b, c))

50 53 4 	Median: 50
60 -83 49 	Median: 49
88 51 93 	Median: 88
91 -59 75 	Median: 75
-64 22 50 	Median: 22
-57 -45 1 	Median: -45
-14 -61 -67 	Median: -61
-99 -78 78 	Median: -78
75 39 88 	Median: 75
-47 93 -8 	Median: -8


# 2. Numpy (4 points)

**Task 1** (0.5 points) <br/>
Create a random array from Gaussian distribution with length of 12 and with sum of its elements equal to 15. Distribution shall be left Gaussian

In [30]:
my_array = np.random.standard_normal(12)
my_array = my_array.dot(15 / my_array.sum())

print(f'Length: {len(my_array)}')
print(f'Sum of elements: {np.sum(my_array)}')

Length: 12
Sum of elements: 14.999999999999943


**Task 2** (0.5 points) <br/>
Create two random arrays $a$ and $b$ with the same length.

Calculate the following distances between the arrays **without using any special function. You may only use basic numpy operations (`np.linalg.*` and other high-level ones are prohibited).**:

* Manhattan Distance
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Euclidean Distance
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Chebyshev Distance
$$ d(a, b) = \underset{i}{max} |a_i - b_i| $$
* Cosine Distance
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2} $$


In [42]:
def calculate_manhattan(a, b):
    return np.sum(np.abs(a - b))

def calculate_euclidean(a, b):
    return np.sqrt(np.sum(np.square(a - b)))

def calculate_chebyshev(a, b):
    return np.max(abs(a - b))

def calculate_cosine(a, b):
    return 1 - np.dot(a, b) / (np.sqrt(np.dot(a, a)) * np.sqrt(np.dot(b, b)))

In [44]:
np.random.seed(2023)

length = np.random.randint(0, 100)
a = np.random.randint(0, 100, length)
b = np.random.randint(0, 100, length)

print('a:\n', a)
print('b:\n', b)
print(f'Manhattan distance: {calculate_manhattan(a, b)}')
print(f'Euclidean distance: {calculate_euclidean(a, b)}')
print(f'Chebyshev distance: {calculate_chebyshev(a, b)}')
print(f'Cosine distance: {calculate_cosine(a, b)}')

a:
 [25 70 55 33 92  3 52 86 96 22 17 53 47 77 39 69 88  3 58 28 81 71 63 48
 32 29 49 49 49 49 53 38 70 15 88 72 47 65 71 22 53  7 45 25 34 49 77 91
 87 45 34 34 11  1 31 69 51 19 40 69 31 43  5 10  7 83 55  6 99 28 46 78
 70 37 63 25 36 40 85 82  5 93 79 26 97 66 58]
b:
 [72 60 26 86 54 24 52 89 79 67 71 78 40 71 36 90 94 47 56 77 15 79  0 95
 39 79 97 72  1 44 27 74 42 56  0  6 62  5 37 77 75 95 20 67 20 12 44 57
 70 47 19 97 18  3 89 10 85 14 87 58 29 77 98 48  3 87 90 70 45 35 19 11
 45 60 64 29 44 41 27 94 36 84  5  7 35 88 47]
Manhattan distance: 2698
Euclidean distance: 362.8443192334696
Chebyshev distance: 93
Cosine distance: 0.2258718653319517


**Task 3** (0.5 points) <br/>
Create a random array of integers with length of 42. Transform the array so that
* Maximum element(s) value is 10
* Minimum element(s) value is -6
* Other values are in interval (-6; 10) without changing the relative order (relation $\frac{x_i}{x_{i-1}}=\frac{\widehat{x}_{i}}{\widehat{x}_{i-1}}$ holds)

In [55]:
def transform(array):
    ini_min, ini_max = np.min(array), np.max(array)
    new_min, new_max = -6.0, 10.0
    
    return (new_max-new_min)*((array-ini_min)/(ini_max-ini_min))+new_min

In [56]:
my_array = np.random.randint(-100, 100, 42)
copy = np.copy(my_array)
input_start = copy.min()
input_end = copy.max()
print('Array before transformation:\n', my_array)
my_array = transform(my_array)
print(f'Min: {np.min(my_array)}')
print(f'Max: {np.max(my_array)}')
print('Array after transformation:\n', my_array)

Array before transformation:
 [ 88 -58 -83  91 -51  79 -82  -4 -32 -87  84 -37  -6 -29 -82  91  -6 -76
 -70 -77  -6 -33  10  40 -25 -40 -40 -81  62  53  40  57  -9 -82 -64 -26
   6  82  53 -86 -13  33]
Min: -6.0
Max: 10.0
Array after transformation:
 [ 9.73033708 -3.39325843 -5.64044944 10.         -2.76404494  8.92134831
 -5.5505618   1.46067416 -1.05617978 -6.          9.37078652 -1.50561798
  1.28089888 -0.78651685 -5.5505618  10.          1.28089888 -5.01123596
 -4.47191011 -5.1011236   1.28089888 -1.14606742  2.71910112  5.41573034
 -0.42696629 -1.7752809  -1.7752809  -5.46067416  7.39325843  6.58426966
  5.41573034  6.94382022  1.01123596 -5.5505618  -3.93258427 -0.51685393
  2.35955056  9.19101124  6.58426966 -5.91011236  0.65168539  4.78651685]


**Task 4** (0.5 points) <br/>
Create an array with shape of $10 \times 3$ with integers from [-12, 4]. Find a column that contains the minimum element of the array.

In [106]:
my_array = np.random.randint(-12, 5, 30).reshape((10, 3))
selected_column = -1
min = 10
column_mins = np.argmin(my_array, axis=0)
for i in range(len(column_mins)):
    cur_min = my_array[column_mins[i]][i]
    print(f'Column №{i} minimum={cur_min} on index={column_mins[i]}')
    if cur_min < min:
        min = cur_min
        selected_column = i
print('Array\'s minimum value: ', min)

print('Shape: ', my_array.shape)
print('Array:')
print(my_array)
print(f'Selected column: {selected_column}')

Column №0 minimum=-10 on index=4
Column №1 minimum=-11 on index=7
Column №2 minimum=-12 on index=0
Array's minimum value:  -12
Shape:  (10, 3)
Array:
[[  4  -7 -12]
 [  4 -10  -3]
 [ -6  -5  -4]
 [  1 -10  -2]
 [-10 -10   0]
 [ -9   2 -10]
 [  4  -9  -2]
 [  4 -11   2]
 [  4 -11   1]
 [ -5   0   3]]
Selected column: 2


**Task 5** (0.5 points) <br/>

Replace all missing values in the following array with the most appropriate quantile, explain why you chose it.

In [4]:
arr = np.random.rand(10)
idx = np.random.randint(0, 10, 4)
arr[idx] = np.nan

print('Array:')
print(arr)

Array:
[0.38805528        nan        nan        nan 0.92541921 0.69329743
 0.225531   0.29300583        nan 0.48978769]


In [7]:
def replace_missing(arr):
    quantile = np.nanquantile(arr, 0.5)
    arr[np.isnan(arr)] = quantile
    return arr

In [6]:
arr = replace_missing(arr)
print('Array with no missing values:')
print(arr)

Array with no missing values:
[0.38805528 0.43892148 0.43892148 0.43892148 0.92541921 0.69329743
 0.225531   0.29300583 0.43892148 0.48978769]


**Answer:** Мы используем функцию nanquantile, чтобы найти наиболее подходящий квантиль, которым в данном случае является медиана (0.5). 
    Медина менее чувствительна к экстремальным значениям, чем среднее значение 
    => она более надёжный показатель центральной тенденции, менее подверженный влиянию выбросов.

**Task 6** (0.5 points) <br/>
Create a function which takes an image ```X``` (3D array of the shape (n, m, 3)) as an input and returns the median and std for every channel (you should get a vector of shape 3, RGB).

In [8]:
def stats_channel(X):
    median = np.median(X, axis=(0, 1))
    std = np.std(X, axis=(0, 1))
    return median, std

In [9]:
n = 19
m = 23
X = np.random.randint(-11, 8, size=(n, m, 3))
print(stats_channel(X))

(array([-2., -2., -3.]), array([5.46385623, 5.47112742, 5.51921551]))


### **Task 7** (1 points) <br/>
Create a function which takes a 3D matrix ```X``` as an input and returns all its unique values along the first axis.

Sample input:

```
np.array(
  [[[1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]],

   [[4, 5, 6],
    [4, 5, 7],
    [4, 5, 6]],

   [[7, 8, 9],
    [7, 8, 9],
    [7, 8, 9]]]
)
```
  
Sample output:

```
np.array(
  [[[1, 2, 3],
    [1, 2, 3]],

   [[4, 5, 6],
    [4, 5, 7]],

   [[7, 8, 9],
    [7, 8, 9]]]
)
```

In [19]:
def get_unique_values(X):
    return np.unique(X, axis=1)

In [21]:
X =  np.random.randint(4, 6, size=(n, 3, 3))
print('Matrix:')
print(X)
print('Unique :')
get_unique_values(X)

Matrix:
[[[5 4 5]
  [5 4 4]
  [5 4 4]]

 [[5 4 4]
  [4 5 5]
  [4 5 5]]

 [[4 5 4]
  [5 4 4]
  [4 4 4]]

 [[4 4 5]
  [4 4 4]
  [5 5 5]]

 [[5 5 5]
  [4 5 4]
  [5 5 4]]

 [[4 4 5]
  [5 5 4]
  [5 5 4]]

 [[5 4 5]
  [4 5 4]
  [4 5 4]]

 [[5 4 5]
  [5 5 5]
  [5 4 4]]

 [[4 5 5]
  [5 5 5]
  [4 5 4]]

 [[5 4 4]
  [4 5 5]
  [4 4 4]]

 [[5 5 4]
  [4 4 4]
  [4 5 5]]

 [[5 5 4]
  [5 4 5]
  [4 5 4]]

 [[4 4 5]
  [4 4 4]
  [4 5 5]]

 [[5 5 5]
  [4 5 4]
  [4 4 4]]

 [[5 4 4]
  [5 5 4]
  [4 4 5]]

 [[5 4 4]
  [4 4 4]
  [5 4 4]]

 [[5 4 5]
  [4 5 4]
  [4 4 5]]

 [[5 4 5]
  [5 5 5]
  [5 5 4]]

 [[4 4 4]
  [5 4 5]
  [5 4 5]]]
Unique :


array([[[5, 4, 4],
        [5, 4, 4],
        [5, 4, 5]],

       [[4, 5, 5],
        [4, 5, 5],
        [5, 4, 4]],

       [[4, 4, 4],
        [5, 4, 4],
        [4, 5, 4]],

       [[5, 5, 5],
        [4, 4, 4],
        [4, 4, 5]],

       [[5, 5, 4],
        [4, 5, 4],
        [5, 5, 5]],

       [[5, 5, 4],
        [5, 5, 4],
        [4, 4, 5]],

       [[4, 5, 4],
        [4, 5, 4],
        [5, 4, 5]],

       [[5, 4, 4],
        [5, 5, 5],
        [5, 4, 5]],

       [[4, 5, 4],
        [5, 5, 5],
        [4, 5, 5]],

       [[4, 4, 4],
        [4, 5, 5],
        [5, 4, 4]],

       [[4, 5, 5],
        [4, 4, 4],
        [5, 5, 4]],

       [[4, 5, 4],
        [5, 4, 5],
        [5, 5, 4]],

       [[4, 5, 5],
        [4, 4, 4],
        [4, 4, 5]],

       [[4, 4, 4],
        [4, 5, 4],
        [5, 5, 5]],

       [[4, 4, 5],
        [5, 5, 4],
        [5, 4, 4]],

       [[5, 4, 4],
        [4, 4, 4],
        [5, 4, 4]],

       [[4, 4, 5],
        [4, 5, 4],
        [5, 4, 5]]

# 3. Pandas & Visualization (4 points)


You are going to work with *Titanic* dataset which contains information about passengers of Titanic:
- **Survived** - 1 - survived, 0 - died (0); **Target variable**
- **pclass** - passengers's class;
- **sex** - passengers's sex
- **Age** - passengers's age in years
- **sibsp**    - is the passenger someones siblings   
- **parch**    - is the passenger someones child or parent
- **ticket** - ticket number    
- **fare** - ticket price    
- **cabin** - cabin number
- **embarked** - port of Embarkation; C = Cherbourg, Q = Queenstown, S = Southampton

**Note** for all visualizations use matplotlib or seaborn but NOT plotly! Plotly's graphics sometimes vanish after saving. In this case the task won't be graded.

**Note** support all your answers with necessary code, computations, vizualization, and explanation. Answers without code and explanation won't be graded.

**Task 0** (0 points) \
Load the dataset and print first 6 rows

In [ ]:
dataset =  ## Your code here
## Your code here

**Task 1** (1 points) <br/>
Answer the following questions:
    
    * Are there any missing values? In what columns?
    * What is the percentage of survived passengers? Are the classes balanced?
    * Were there more males or females?
    * What what the least popular port of embarkation?
    * How many passenger classes (pclass) were there on Tinanic?
    * What is the overall average ticket fare? And for every passenger class?
Please, write not only the answers but the code, proving it.

In [ ]:
## Your code here

**Task 2** (0.5 points) <br/>
Visualize age distribution (you may use a histogram, for example).

    * What is the minimal and maximum ages of the passengers? Visualize it on the plot
    * What is the median age? And among males and females separately? Visualize it on the separate plot
    * Make conclusions about what you see on the plots

In [ ]:
## Your code here

**Task 3** (1 points) <br/>
Find all the titles of the passengers (example, *Capt., Mr.,Mme.*), which are written in the column Name, and answer the following questions:

    * How many are there unique titles?
    * How many are there passengers with every title?
    * What is the most popular man's title? And woman's title?
    
**Hint** You may select the title from the name as a word which contains a dot and is not middle name.

In [ ]:
## Your code here

**Task 4** (0.5 points) <br/>
Is there correlation between *pclass* and *ticket price*? Calculate mean price for each class and visualize price distribution for each class as well. Make conclusions about what you see on the plot

Hint: you could make one or several plot types i.e.  box, violine, pair, histogram (see additional notebooks for Seminar 1 "Visualization with Seaborn"). Main point here is to **choose** plots wisely and **make meaningful conclusions**



In [ ]:
## You code here

**Task 5** (0.5 points) <br/>
The same question as in task 4 about correlation between *embarked* and *ticket priсe*.

In [ ]:
## You code here

**Task 6** (0.5 points) <br/>
Visualize age distribution for survived and not survived passengers separately and calculate the mean age for each class. Are they different? Provide the same visualization for males and females separately. Make conclusions about what you see on the plots

In [ ]:
## You code here